version: "3.9"

services:
  theft-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-api
    restart: unless-stopped
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - ../Detect.py:/app/tds/Detect.py:ro
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-retrieval-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.video_retrieval_worker
    volumes:
      - ../Detect.py:/app/tds/Detect.py:ro
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-analysis-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-analysis-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.video_analysis_worker
    volumes:
      - ../Detect.py:/app/tds/Detect.py:ro
      - ../session:/app/session
      - ./models:/app/tds/models
