version: "3.9"

services:
  theft-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-api
    restart: unless-stopped
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-retrieval-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.video_retrieval_worker
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-analysis-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-analysis-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.video_analysis_worker
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-grouping-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-grouping-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.grouping_worker
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-confidence-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-confidence-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.theft_confidence_worker
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models

  theft-kiosk-analysis-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: theft-detection-kiosk-analysis-worker
    restart: unless-stopped
    env_file:
      - .env
    command: python -m app.workers.kiosk_analysis_worker
    volumes:
      - ../session:/app/session
      - ./models:/app/tds/models
